// Code generated by "stringer -type=TicTacToeStatus"; DO NOT EDIT

package chatbot

import "fmt"

const _TicTacToeStatus_name = "TicTacToeStatusGoTicTacToeStatusDrawTicTacToeStatusLose"

var _TicTacToeStatus_index = [...]uint8{0, 17, 36, 55}

func (i TicTacToeStatus) String() string {
	if i < 0 || i >= TicTacToeStatus(len(_TicTacToeStatus_index)-1) {
		return fmt.Sprintf("TicTacToeStatus(%d)", i)
	}
	return _TicTacToeStatus_name[_TicTacToeStatus_index[i]:_TicTacToeStatus_index[i+1]]
}
